### ISSUE TITLE
Create microsite for the documentation

### ISSUE THREAD

**Issue by sanjivsahayamrea** [scalaz/testz#19]
From the looks of the repo, there is some documentation under `docs/src/main/tut` which I presume would get published through a microsite.

**Comment by edmundnoble** [comment]
Yeah, I need to do that.

**Comment by NeQuissimus** [comment]
Let me complete my example in https://github.com/NeQuissimus/test-and-stuff and then you can just go through the motions without running into the disaster I had to deal with in ZIO :D

**Comment by edmundnoble** [comment]
Done, [here](http://scalaz.github.io/testz).

**Comment by sanjivsahayamrea** [comment]
👍
