### ISSUE TITLE
Consider applicative DSL

### ISSUE THREAD

**Issue by jdegoes** [scalaz/testz#6]
Goals:

 * Parallelize tests to the extent possible 
 * Add documentation at arbitrary nodes
 * Support singletons, lists, maps, whatever `F[_]` shaped structure
 * Print out documentation for a test without running it
 * Filter over tests to implement test-only type functionality

Etc.

**Comment by edmundnoble** [comment]
Fortunately, the DSL as it is right now already supports parallelism at the test level. You can also add documentation by defining custom suite types; the same goes with printing docs for a test without running them.

EDIT: Technically the DSL makes test registration "monoid homomorphisms from a free monoid", so it's actually more powerful from the consumer-end than `Applicative`.

**Comment by edmundnoble** [comment]
Right, this is done now. Though the test DSL is totally decoupled from the runner, so it's very possible to use any DSL you want, all of the DSLs I have right now are monoidal.

**Comment by edmundnoble** [comment]
Now that we have `DocHarness`, I think it's clear that we fully support this.
